### ISSUE TITLE
[Question] override podbot.cfg by custom folder?

### ISSUE THREAD

**Issue by mrc4tt** [APGRoboCop/podbot_mm#5]
Hi,

Is it possible to override the podbot.cfg being loaded from the custom folder (without it being locked to the original folder?)

Custom example:
`addons/podbot-1/podbot.cfg`

Has tried editing on podbot.cfg, but sadly it will only accept the changes if I edit manually from the original folder: `addons/podbot/podbot.cfg`

**Comment by mrc4tt** [comment]
@APGRoboCop are you still active in development podbot_mm?

**Comment by APGRoboCop** [comment]
Oh sorry missed that. I will need to look into that im not sure if KWo only allows to load the .cfg if the folder is named as /podbot. But I am currently offline from coding for a few days

**Comment by mrc4tt** [comment]
@APGRoboCop 

Any updates? Could be nice, if its possible to override the default podbot folder name.

If you have a example source-code, how I can do it self. So i could do compile manually.

Example: `-serverid 1337`
Output: `cstrike/addons/podbot_1337/podbot.cfg`

Plugin will now understand and read new structures, without being locked to default.

**Comment by bbashy** [comment]
Can it read from where the .so file got loaded from?

`linux addons/podbot_1337/podbot_mm_i386.so` so configs within addons/podbot_1337 would be loaded.

**Comment by APGRoboCop** [comment]
Well, it appears it only works if the directory and .cfg file exist as "addons/podbot/podbot.cfg", if I'm not mistaken...

https://github.com/APGRoboCop/podbot_mm/blob/master/dll.cpp#L1910

But if you want to load another .cfg you may have to rename the default .cfg and put that to one side. Also if you want the server to load a different .cfg from Podbot or a different named Podbot folder, you could add this in either autoexec.cfg or server.cfg:

> exec addons/podbot_1337/podbot.cfg

**Comment by mrc4tt** [comment]
> But if you want to load another .cfg you may have to rename the default .cfg and put that to one side. Also if you want the server to load a different .cfg from Podbot or a different named Podbot folder, you could add this in either autoexec.cfg or server.cfg:

The problem is that it will continue to load the normal podbot.cfg file from the `addons/podbot` path.

Which it shouldn't do, as I'm running a custom setup of CS1.6 servers with a separate podbot for each server.

For example, if I execute `exec addons/podbot_929/podbot.cfg`
The server will still execute `addons/podbot/podbot.cfg` as the original default (which it should never do)

Which I can see is run by default according to the source code. And therefore want an option for this to be changed. or override with the command line: `+podbot addons/podbot_929` or similar.

Translated with DeepL.com (free version)

**Comment by mrc4tt** [comment]
> But if you want to load another .cfg you may have to rename the default .cfg and put that to one side. Also if you want the server to load a different .cfg from Podbot or a different named Podbot folder, you could add this in either autoexec.cfg or server.cfg:

The problem is that it will continue to load the normal podbot.cfg file from the `addons/podbot` path.

Which it shouldn't do, as I'm running a custom setup of CS1.6 servers with a separate podbot for each server.

For example, if I execute `exec addons/podbot_929/podbot.cfg`
The server will still execute `addons/podbot/podbot.cfg` as the original default (which it should never do)

Which I can see is run by default according to the source code. And therefore want an option for this to be changed. or override with the command line: `+podbot addons/podbot_929` or similar.

**Comment by APGRoboCop** [comment]
Well I didn't create POD-Bot nor made a lot of modifications to them. If you want me to recompile them to suppress loading that default .cfg then I could that, just for you?

**Comment by mrc4tt** [comment]
> Well I didn't create POD-Bot nor made a lot of modifications to them. If you want me to recompile them to suppress loading that default .cfg then I could that, just for you?

Could be nice, @APGRoboCop if you can do that. 👍
More so the podbot.cfg from the separate folder is loaded from the custom folder (reserved) without its stock default loading from addons/podbot/podbot.cfg :-) 

We use Debian 12 on all our servers.

**Comment by APGRoboCop** [comment]
[podbot_mm.tar.gz](https://github.com/APGRoboCop/podbot_mm/files/14522301/podbot_mm.tar.gz)
Well here goes nothing...
